[package]
name = "hashcode2021"
description = "Hash Code 2021"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
rand = "0.8"
log = "0.4"
env_logger = "0.8"
ctrlc = { version = "3.1", features = ["termination"] }

